// game
export const SET_GAME_NAME = "SET_GAME_NAME";
export const ADD_PLAYER = "ADD_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const INCREMENT_PLAYER_SCORE = "INCREMENT_PLAYER_SCORE";
export const DECREMENT_PLAYER_SCORE = "DECREMENT_PLAYER_SCORE";
export const NEXT_ROUND = "NEXT_ROUND";
export const RESET_GAME = "RESET_GAME";
export const CHANGE_PLAYER_NAME = "CHANGE_PLAYER_NAME";

// config
export const SET_TALLY = "SET_TALLY";
export const SET_EDITING_MODE = "SET_EDITING_MODE";
export const TOGGLE_HISTORY = "TOGGLE_HISTORY";
export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS";
export const TOGGLE_ALL_FALSE = "TOGGLE_ALL_FALSE";
export const TOGGLE_DELETE_STATE = "TOGGLE_DELETE_STATE";
